site_name: timetables.app
theme:
  name: 'material'
  logo: 'logo.png'
  language: 'pl'
nav:
  - './index.md'
  - './responsibilityArea.md'
  - './search/index.md'
  - './schedule/index.md'
  - './community/index.md'
